#!/bin/bash

# this script will ssh into all hostnames/IPs
# passed to it and run whichever command specified

[[ -n "$1" ]] || { echo "Usage: ssh_all \"command\" server1 server2 server3 ..."; exit 0 ; }

COMMAND=$1
shift

for SERVER in $@; do
     echo "----------------------"
     echo "Running '$COMMAND' on $SERVER"
     echo $COMMAND | ssh $SERVER /bin/bash
     echo "----------------------"
     echo ""
done
