#!/bin/bash

login="zach"
pass=
host="sftp://vaiya.arda.at"
remote_dir="/torrents/completed"
local_dir=$1
#logfile="/home/zach/.torrent-pull.log"


trap "rm -f /tmp/synctorrent.lock" SIGINT SIGTERM

if [ -e /tmp/synctorrent.lock ]
then
  echo "Synctorrent is running already."
  exit 1
else

  touch /tmp/synctorrent.lock
  echo "------------------------------------" >> $logfile
  date >> $logfile

  lftp -u $login,$pass $host << EOF
  set mirror:use-pget-n 6
  mirror -p -c -P4 $remote_dir $local_dir
  quit
EOF

  rm -f /tmp/synctorrent.lock
  exit 0

fi
