#!/usr/bin/env zsh
# Clone Github repo and cd into it

# Do nothing if no args were provided
[[ -z "$1" ]] && return 1

git clone "git@github.com:${1}" || return $?
cd "$(awk -F '/' '{print $NF}' <<< $1)" || return $?

confirm "Overwrite local tags when fetching 'origin'?" \
  && git config set --local --append 'remote.origin.fetch' '+refs/tags/*:refs/tags/*'
