#!/usr/bin/env zsh
# Ask the user to confirm a question
# Argument is the question to ask
local response

while true; do
  vared -e -p "$* [y/n] " -c response || return 2
  [[ $response =~ [yY] ]] && return 0
  [[ $response =~ [nN] ]] && return 1
  unset response
done
