#!/usr/bin/env zsh
# Update dotfiles plugins
local targets="${@:-dot vim zsh sub}"

[[ $targets =~ "dot" ]] \
  && (dot && git fetch && git merge)

# wrapped in a VeryLazy autocmd because lazy.nvim loads its commands after '-c' commands would run
[[ $targets =~ "vim" ]] \
  && (nodot && nvim -c 'autocmd User VeryLazy Lazy! sync')

[[ $targets =~ "zsh" ]] \
  && (nodot && zsh -ic "zinit update --all")

[[ $targets =~ "sub" ]] \
  && (dot && echo "Updating submodules..." && git subf)
