#!/usr/bin/env zsh
# Update dotfiles plugins
local targets="${@:-dot vim zsh sub}"

[[ $targets =~ "dot" ]] \
  && (dot && git fetch && git merge)

[[ $targets =~ "vim" ]] \
  && (nodot && nvim -u "${XDG_CONFIG_HOME}/nvim/init.vim" -i NONE -c 'PlugUpgrade' -c 'PlugUpdate' -c ':qa')

[[ $targets =~ "zsh" ]] \
  && (nodot && zsh -ic "zinit update --all")

[[ $targets =~ "sub" ]] \
  && (dot && echo "Updating submodules..." && git subf)
