#!/usr/bin/env bash

# Does 'adb sync' backwards (device->host)

if [[ -z $1 ]]; then  # check that we have arguments
  echo "Usage: $(basename "$0") <device_path> [local_path]"
  exit 1
elif [[ -z $2 ]]; then  # if we do, set our local dir
  local_dir=$(pwd)
else  # unless the user specified a different one
  local_dir=$2
fi

# assign filenames
remote_dir=$1
temp_dir=/tmp
local_list="$temp_dir/adb_local.$RANDOM"
remote_list="$temp_dir/adb_remote.$RANDOM"
update_list="$temp_dir/adb_update.$RANDOM"

# get remote and local file lists
adb shell ls "$remote_dir" > $remote_list
ls "$local_dir" -1 > $local_list

# we don't want clobber any existing files
if [[ -e $update_list ]]; then
  echo "$update_list exists, please remove it"
  exit 1
fi

while IFS=  read -r q; do
  # Remove non-printable characters (are not visible on console)
  l=$(echo "${q}" | sed 's/[^[:print:]]//')
  # Populate files to update
  if ! grep -q "$l" $local_list; then
    echo "$l" >> $update_list
  fi
done < $remote_list

cd "$local_dir" || exit 1

while IFS=  read -r q; do
  # Remove non-printable characters (are not visible on console)
  l=$(echo "${q}" | sed 's/[^[:print:]]//')
  echo "Get file: $l"
  adb pull -p "$remote_dir/$l"
done < $update_list

# clean up
rm -f $local_list $remote_list $update_list
