#!/usr/bin/env zsh

# Useful zsh function to interactively rename one or more files.
# Simply run `imv file1 file2 ...`
# Edit each line to how you want it. When at the last file, zsh will rename them.

imv() {
  local src dst
  for src; do
    [[ -e $src ]] || { print -u2 "$src does not exist"; continue }
    dst=$src
    vared dst
    [[ $src != $dst ]] && mkdir -p $dst:h && mv -n $src $dst
  done
}

imv $1
