#!/usr/bin/env bash

# this script will run through the current conserver hosts file
# and verify each address is live, and comment out those who aren't


# input file should be a tab-delimited or space-delimited file with
# the first column IP addresses in the first column, and hostnames second

SOURCE=$1

check_ip() {
     IP=$(echo "$LINE" |grep -o '[0-9]*[0-9]\.[0-9]*[0-9]\.[0-9]*[0-9]\.[0-9]*[0-9]')
     ping -c1 -w2 $IP > /dev/null
#     echo ping -c1 -w2 $IP
     if [ $? -eq 0 ]
     then
          echo "$LINE"
     else
          echo "#$LINE"
     fi;
}

while read LINE; do
     (check_ip $LINE&)
#     check_ip $LINE
done < $SOURCE
