#!/usr/bin/env bash

# Checks if a server (or servers) alive (using ICMP PING heartbeats)

#Check for Command Line parmeters.  -V supresses machines with a Hostname ending in 'v'
check_health () {

while read -r server; do
        ping -c 1 -w 1 "$server" > /dev/null
        if [ $? -eq 0 ]
        then
                echo -e "\033[00;32m[LIVE]\t\033[0m$server"
        else
                echo -e "\033[00;31m[DEAD]\t\033[0m$server"
        fi;
done
}

#if search term is empty, return usage info.
if [[ $1 == "" ]]
then
     echo "Please provide server list"
else
        #do it!
        check_health<"$1" | column -t
fi;
